version: '3'
services:
  streambot:
    build:
      context: ./streambot
    env_file: ./streambot.env
    depends_on:
      - icecast
    # logging:
    #   driver: awslogs
    #   options:
    #     awslogs-group: klulz
    #     awslogs-region: us-west-2
    #     awslogs-stream-prefix: icecast
  icecast:
    build:
      context: ./icecast
    ports:
      - "8000:8000"
    volumes:
      - ./icecast.xml:/etc/icecast2/icecast.xml
      - ./icecast-logs:/var/log/icecast2
    # logging:
    #   driver: awslogs
    #   options:
    #     awslogs-group: klulz
    #     awslogs-region: us-west-2
    #     awslogs-stream-prefix: ice3
